name: zenoh_counter_dart
description: A sample command-line application with basic argument parsing.
version: 0.1.1
publish_to: none
repository: https://github.com/hugo-bluecorn/zenoh-counter-dart

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  zenoh:
    git:
      url: https://github.com/hugo-bluecorn/zenoh_dart.git
      path: package

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.2.0
